### PR TITLE
Ruby 1.9 Compatibility

### PR DESCRIPTION
**Pull request by gf3**
The future is now!

### CODE REVIEW

**Comment by tobie** [comment]
Are those changes compatible with ruby 1.8.x ?

**Comment by gf3** [comment]
Yes, I ran all the tests and generated docs on both `1.8.7` and `1.9.2`. You do have a couple failing tests, however those are unrelated to my changes.

**Comment by tobie** [comment]
> You do have a couple failing tests, however those are unrelated to my changes.

Not surprised. :-/

**Comment by tobie** [comment]
[Pulled](http://github.com/tobie/pdoc/commit/5152ce5825c3411de7562fe2fb03a2fc25f1fe3c). Thanks!

**Pull request closed without merging**
